41기 류건호 로그인 사인업 기능 리팩토링
wecode-bootcamp-korea/41-1st-Dwae-Getarian-backend pull request #10
Opened 2023-01-09 06:09 UTC by kakao513

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [x] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
로그인 사인업 기능 리팩토링

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
로그인 사인업 기능 리팩토링

<br />

## :: 테스트 결과 이미지
![스크린샷 2023-01-09 오후 3 08 41](https://user-images.githubusercontent.com/104866923/211249392-18531a0d-e378-4149-b29c-2e20b257787b.pn
![스크린샷 2023-01-09 오후 3 08 35](https://user-images.githubusercontent.com/104866923/211249400-29ffaa00-2acb-48fb-9f31-311fb2dc8ff9.png)
g)
![Uploading 스크린샷 2023-01-09 오후 3.08.47.png…]()
![스크린샷 2023-01-09 오후 3 08 58](https://user-images.githubusercontent.com/104866923/211249418-f18e4b07-8f6b-4387-be9b-ad061eadd097.png)

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-01-11 02:07 UTC, bigfanoftim requested changes
건호님 여전히 하나도 해결되지 않았네요

로그인/회원가입 코드만 올라오도록 수정해주세요

2023-01-11 06:09 UTC, bigfanoftim requested changes
<img width="337" alt="image" src="https://user-images.githubusercontent.com/62135254/211730435-826f4241-d382-481a-b92a-ff23c8498deb.png">

건호님 PR에 어떤 코드가 올라왔느지 확인하셨나요?

2023-01-11 09:09 UTC, kakao513 commented
> <img alt="image" width="337" src="https://user-images.githubusercontent.com/62135254/211730435-826f4241-d382-481a-b92a-ff23c8498deb.png">
> 
> 건호님 PR에 어떤 코드가 올라왔느지 확인하셨나요?

이게 사실 이 부분만 올라와야된다고 하신 말씀을 제가 잘못 이해한 것 같네요... merge를 메인과 해보아도 반영이 안되는데 어떻게 하면 좋을까요?? ㅠ

2023-01-12 06:29 UTC, bigfanoftim approved these changes
LGTM 👍

2023-01-12 06:29 UTC, merged