41기 류건호 주문 기능 분리
wecode-bootcamp-korea/41-1st-Dwae-Getarian-backend pull request #6
Opened 2023-01-04 07:15 UTC by kakao513

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 데이터베이스 작업
- [x] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
- email, password를 이용한 로그인 기능 구현 (예시)

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- API 호출 시 필요한 값들에 대한 유효성 검사 (예시)

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-01-09 02:21 UTC, bigfanoftim requested changes
main에 머지된 내용 이쪽으로도 머지해서 
이전 PR 수정사항 안보이도록 해주세요.

2023-01-09 02:21 UTC, bigfanoftim commented on api/routes/orderRoutes.js
> +// , jwtVerify
```suggestion
```

2023-01-09 02:21 UTC, bigfanoftim commented on api/routes/orderRoutes.js
> +routes.post("/items/:id", asyncErrorHandler(createOrdersRequest));
userId를 param으로 받는건가요?

2023-01-09 02:21 UTC, bigfanoftim commented on api/services/orderService.js
> +    const totalCost = paymentData["total_cost"];
구조분해할당 해주세요

2023-01-09 02:21 UTC, bigfanoftim commented on api/controllers/orderController.js
> +	const userId = req.params.userId;
여기서도 계속 userId를 params로 받고 계시네요.

2023-01-09 08:29 UTC, kakao513 commented on api/routes/orderRoutes.js
> +routes.post("/items/:id", asyncErrorHandler(createOrdersRequest));
토큰으로 아직 받는 걸 하지 못해서 이런식으로 일단 진행하고 있었습니다.. ㅎ

2023-01-10 02:03 UTC, Jon9Beom commented on api/controllers/orderController.js
> +	}
전체적으로 controller에서 예측되는 예외처리를 직접 if의 실행문을 통해 reponse하고 있는데, globalErrorHandler와 async Wrapper 함수를 만들어 놓았으니 미들웨어로서 일괄적으로 처리하는 것이 좋아보입니다. if문에서는 error 객체를 만들고 status code와 message만 부여해서 throw해주면 될 것 같아요.

2023-01-10 02:10 UTC, Jon9Beom commented on api/models/orderDao.js
> +async function createOrderTable(userId, totalCost) {
```suggestion
async function createOrder(userId, totalCost) {
```

2023-01-10 02:11 UTC, Jon9Beom commented on api/models/orderDao.js
> +    return orderTable;
```suggestion
			return appDataSource.query(
				`
					INSERT INTO orders 
						(user_id, total_cost) 
					VALUES (?, ?)
    		`, [ userId, totalCost ]);
```
불필요한 변수 선언 없이 바로 return 해주시면 될 것 같습니다.

2023-01-10 02:12 UTC, Jon9Beom commented on api/models/orderDao.js
> +async function createOrdersRequest(orderId, products) {
```suggestion
async function createOrderProducts(orderId, products) {
```
query문을 보면 order products를 create한다가 맞을 것 같네요.

2023-01-10 02:15 UTC, Jon9Beom commented on api/models/orderDao.js
> +        return requestResult;
```suggestion
        const values = products.map((product) => {
            return [ orderId, product.id, product.quantity ];
        });
    
        return appDataSource.query(`
	  INSERT INTO order_product 
	    (
	      orders_id, 
	      product_id, 
	      quantity
	    ) VALUES ?;
        `, [values]);
```
보다 보기 좋고 간단하게 쓰일 수 있을 것 같습니다.

2023-01-10 02:16 UTC, Jon9Beom commented on api/models/orderDao.js
> +async function deleteOrdersRequest(userId, orderId) {
```suggestion
async function deleteOrder(userId, orderId) {
```

2023-01-10 02:17 UTC, Jon9Beom commented on api/models/orderDao.js
> +			return requestResult;
```suggestion
			return appDataSource.query(
				`
					DELETE FROM orders
					WHERE user_id = ? AND order_id = ?
				`, [ userId, orderId ]);
```

2023-01-10 02:18 UTC, Jon9Beom commented on api/routes/orderRoutes.js
> +routes.delete("/", jwtVerify, asyncErrorHandler(deleteOrder));
```suggestion
routes.delete("", jwtVerify, asyncErrorHandler(deleteOrder));
```
보다 RESTful한 api가 설계될 수 있도록 엔드포인트 끝이 (/)로 작성되는건 지양해주세요 :)

2023-01-10 05:58 UTC, kakao513 commented on api/routes/orderRoutes.js
> +routes.delete("/", jwtVerify, asyncErrorHandler(deleteOrder));
넵넵 반영했습니다

2023-01-10 06:05 UTC, kakao513 commented on db/migrations/20230103042951_create_cart_table.sql
> +>>>>>>> main
넵넵!

2023-01-10 06:05 UTC, kakao513 commented on api/controllers/orderController.js
> +	}
넵넵!

2023-01-10 06:06 UTC, kakao513 commented on api/controllers/orderController.js
> +	const deleteRequest = await deleteOrder(userId, orderId, refundData);
갑자기 이름을 바꾸면서 Human error가 난것 같네요 ㅎ

2023-01-10 06:06 UTC, kakao513 commented on api/controllers/orderController.js
> +	if (!userId || !orderId || refundData) {
넵넵!

2023-01-10 06:06 UTC, kakao513 commented on api/controllers/orderController.js
> +	const refundData = req.body;
넵 알겠습니다 배포 전 어디서 에러가 났는지 확인하기 위해 적어놓았습니다 지우겠습니다

2023-01-10 06:06 UTC, kakao513 commented on api/controllers/orderController.js
> +	}
넵넵!

2023-01-10 06:07 UTC, kakao513 commented on api/controllers/orderController.js
> +async function createOrdersRequest(req, res) {
넵넵!

2023-01-10 09:31 UTC, bigfanoftim approved these changes

2023-01-10 09:31 UTC, merged