41기 류건호
wecode-bootcamp-korea/41-1st-Dwae-Getarian-backend pull request #8
Opened 2023-01-06 07:50 UTC by kakao513

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
카트 물품 삭제 feature 구현

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
카트 물품 삭제 feature 구현

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지

<br />

## :: 기타 질문 및 특이 사항
- 제가 작성한 함수의 로직이 너무 복잡하다고 생각이 됩니다. 더 효율적인 방법이 없을까요? (예시)

2023-01-06 09:08 UTC, bigfanoftim commented
라벨 변경전 PR 상태 확인해주세요~

2023-01-09 09:14 UTC, bigfanoftim requested changes
전체적으로 들여쓰기가 하나도 맞지 않아 읽기가 쉽지 않습니다.

PR올리시고 Files changed탭을 꼭 확인해 주세요

2023-01-09 09:14 UTC, bigfanoftim commented on api/middlewares/auth.js
> +}
들여쓰기 이게 맞는걸까요?ㅠ

2023-01-09 09:14 UTC, bigfanoftim commented on api/controllers/cartController.js
> +async function insertCartItems(req, res) {
```suggestion
async function insertCartItem(req, res) {
```
product가 하나인 것 같으니 Items가 아니라 단수형으로 작성하는 것이 좋아보입니다.

2023-01-09 09:14 UTC, bigfanoftim commented on api/controllers/cartController.js
> +    const requestResult = await cartService.insertCartItems(userId, product);
service 네임도 마찬가지입니다.

2023-01-09 09:14 UTC, bigfanoftim commented on api/controllers/cartController.js
> +	const cartItems = req.body["cart_items"];
- `cart_items` 라고 작성하면 정확히 뭘받는건지 알아볼 수 없습니다.
- camelCase로 통일해주세요.
- delete 메소드에 대해서는 body를 사용하라는 명시가 정확히 없어 굳이 사용하지 않는 것이 더 좋겠습니다. `DELETE :3000/carts?...` 로 변경해주세요!

2023-01-09 09:14 UTC, bigfanoftim commented on api/services/cartService.js
> +    return result;
```suggestion
    return await cartModel.insertCartItems(userId, product);
```

2023-01-09 09:14 UTC, bigfanoftim commented on api/services/cartService.js
> +}
```suggestion
	return await cartModel.getCartItems(userId);
}
```

2023-01-10 02:24 UTC, Jon9Beom commented
건호님~ 이전 [PR](https://github.com/wecode-bootcamp-korea/41-1st-Dwae-Getarian-backend/pull/6)에서 제가 남겨드린 코멘트와 중복적으로 해당되는 부분이 있기도 하고, 호준님이 남겨주신 피드백에서 반영이 미처 안된 부분도 있어서요. 다시 한 번 확인 후 수정 부탁드리겠습니다!

![image](https://user-images.githubusercontent.com/94527515/211447623-7e89432f-37a1-4a88-abe8-45ac6dcf7782.png)
![image](https://user-images.githubusercontent.com/94527515/211447646-dd06e0a8-2a3e-4765-9a73-f9e017c3b6b8.png)

2023-01-10 05:33 UTC, kakao513 commented
> 건호님~ 이전 [PR](https://github.com/wecode-bootcamp-korea/41-1st-Dwae-Getarian-backend/pull/6)에서 제가 남겨드린 코멘트와 중복적으로 해당되는 부분이 있기도 하고, 호준님이 남겨주신 피드백에서 반영이 미처 안된 부분도 있어서요. 다시 한 번 확인 후 수정 부탁드리겠습니다!
> 
> ![image](https://user-images.githubusercontent.com/94527515/211447623-7e89432f-37a1-4a88-abe8-45ac6dcf7782.png) ![image](https://user-images.githubusercontent.com/94527515/211447646-dd06e0a8-2a3e-4765-9a73-f9e017c3b6b8.png)

혹시 이거 Delete에서 요구하시는 방향이 잘 이해가 안되서 그런데 조금 더 자세히 설명 가능하실까요?

2023-01-10 09:33 UTC, bigfanoftim approved these changes

2023-01-10 11:22 UTC, merged